### ISSUE TITLE
zeds regen health while burning

### ISSUE THREAD

**Issue by aortez** [theCrius/project-zomboid-random-zombies-full#9] opened 2023-08-06 07:22 UTC
**Describe the bug**
I believe that this mod is causing zeds to regenerate health while burning.  However I am completely new to pz modding, and relatively new to the game, so I could certainly be incorrect.

I think the cause is this code:
https://github.com/theCrius/project-zomboid-random-zombies-full/blob/2da53e8807c043ab1a19e8e2ad65d08786a31d0b/Contents/mods/RandomZombiesDayAndNight/media/lua/server/rzf_zombiesManager.lua#L180C24-L195
``` lua
    -- update toughness
    if distribution.normal ~= 100 then
      if not zombie:getAttackedBy() then -- I think this check may be ignoring if the zed is on fire
        zid = utilities.hash(zid)
        local slice3 = utilities.hashToSlice(zid)
        local health = 0.1 * ZombRand(4)
        if slice3 < distribution.fragile  then
          health = health + 0.5
        elseif slice3 < distribution.tough then
          health = health + 1.5
        else
          health = health + 3.5
        end
        zombie:setHealth(health)
      end
    end
```

I'm not sure how the ` zombie:getAttackedBy()` API works, but I suspect it reflects when a player is attacking a given zed, and the intent of the conditional check is to avoid avoid updating a given zed's health while the player is fighting with it.  I'm guessing that if a zed is on fire, but the player has not recently hit the zed, then the zed's health will possibly be updated, or something similar to that.  I suppose I should look around for the API docs...

**To Reproduce**
1. Load the game in debug mode
1. Create a new game, using this mod and Combat Text (so you can observe the zed's health).
1. Spawn items needed to create and light a campfire.  
1. Light the campfire.  
1. Spawn some zeds and cause them to walk into the fire by taunting them.

**Observed Behavior**
The zeds will take fire damage over time (as expected), but  their health will also occasionally increase while they are burning (not expected).  My observation is that not only does their health regen, but their max health can also increase.

**Expected behavior**
Zeds that are on fire should not regain health, nor should their max health increase.  Their health should only decrease.

**Specification:**
- version 41.78.16 (steam)
- Game mode: solo
- SandboxVars block for the mod:
There are a lot of vars for this mod, is there perhaps an easy way to dump these or maybe just copy from a config file somewhere? 

**Additional context**
Let me know if there is anything else I can do to help.  I am new to pz and pz modding, but I have a bit of free time to burn, so I'm happy to help however.

This mod seems like quite a boon to pz and its community, so thank you for your work.

**Comment by theCrius** [comment] 2023-08-06 09:06
Thank you for the detailed report @aortez. Stupid questions first: Did you test this with only this mod active?

I'm currently swamped with an house move so I won't be able to jump right onto this but I appreciate your thinking on the issue. The API unfortunately have zero documentation so it's always a sort of trial and error.

The `getAttackedBy` [in the APIs](https://projectzomboid.com/modding/index.html) seems to be related to the character getting attacked: `https://projectzomboid.com/modding/zombie/characters/IsoGameCharacter.html#getAttackedBy()`

If it was the zombies, it would use this object instead: `https://projectzomboid.com/modding/zombie/characters/IsoZombie.html`

So my reasoning is that the mod is preventing the zombies to be updated if it's the time (default every 7500msec) and the character is being actively attacked.

Now, something we can try, is raise the interval to the maximum suggested (1 minute, 60000msec) to see if you can more easily note when this happens.

If you are a bit used to scripting, you can also just add a printout in that function, just under the `zombie:setHealth(health)` which will be something like `print("[RZF DEBUGGING] Updating Zombies Health: ", health)`. It will give you a bunch of lines each time it runs (because it will update all active zombies) but it should help have a better understanding of when to check for health changes while burning. If you pair it with some mod that show the health of zombies for example, like [combat text](https://steamcommunity.com/sharedfiles/filedetails/?id=2286124931) (you can disable the floating text and leave only the bars) that would be easier as well.

Be aware that if you try using also that mod (or any other) you should also check just with that mod, to be sure the issue is not coming from elsewhere.

I know, it's tedious, welcome to project zomboid modding 😆

**Comment by aortez** [comment] 2023-08-06 17:41
Howdy @theCrius. First, good luck with your move, I hope it goes smooth and you are happy with the end result.  Please do not let me distract you unless you are in the mood to be distracted.

Then:
> [Good] questions first: Did you test this with only this mod active?

Pretty much, I whittled my mod list down to just this mod, Combat Text, and Mod Manager.  Removing this mod removes the problem, re-adding it reintroduces it.  Also, commenting out the specified block of code "fixes" the issue, uncommenting it causes the issue to return.

I'll do some messing around to see if I can better understand what is going on and I'll post again once I come up with something.  Thanks for the tips (and nice repo, README, etc).

**Comment by aortez** [comment] 2023-08-06 21:16
Hmm, I think you're mistaken about the [zombie:GetAttackedBy() check](https://github.com/theCrius/project-zomboid-random-zombies-full/blob/2da53e8807c043ab1a19e8e2ad65d08786a31d0b/Contents/mods/RandomZombiesDayAndNight/media/lua/server/rzf_zombiesManager.lua#L182), as `zombie.characters.IsoZombie` inherits from `zombie.characters.IsoGameCharacter`, thus it also has the `GetAttackedBy()` method.  So this method can be called from a character or zombie object.  In the case here, I think it is being called on a zombie object.

I did some testing (by just adding print statements to the existing mod code), and I found that this `zombie:GetAttackedBy()` check returns `nil` until I hit a given zombie. I sped up time and it seems this status persists for quite a long time. I'm not sure if it expires or not.

So again, this is what I think is happening:
``` lua
if distribution.normal ~= 100 then
  -- If player has hit this zombie, do not update its health.
  if not zombie:getAttackedBy() then
    ... -- update health
  end
end
```

_However_, the "AttackedBy" status seems to immediately expire after the zombie takes fire damage. This means any burning zed will be eligible to have its health updated, unless the player strikes the zed between when it takes fire damage and when the mod's next update cycle runs.

Here's what my proposed fix looks like:
``` lua
if distribution.normal ~= 100 then
  -- If player has hit this zombie, do not update its health.
  -- Also exclude burning zombies from health updates.
  if not zombie:getAttackedBy() and not zombie:isOnFire() then
    ... -- update health
  end
end
```

Here's a PR with a possible fix:
https://github.com/theCrius/project-zomboid-random-zombies-full/pull/10

Keep in mind that I'm %100 new to PZ modding and also lua, so I could be doing silly things without knowing.  Thanks and please let me know if I can do anything else to help here.

**Comment by theCrius** [comment] 2023-08-06 23:47
You are absolutely right in the inheritance between the two objects. I completely forgot about that.

I'll find some time to test this next weekend and push an update merging your change if I don't see any weird behaviour.
Good find and thanks for the PR ❤️

**Comment by aortez** [comment] 2023-08-07 01:26
It is great to be able to contribute :bow: .  I'm actually playing this game these days, so I'll of course let you know if I find any issues with the change.

**Comment by theCrius** [comment] 2023-08-16 20:19
@aortez as you have probably imagined I haven't had the time to test nothing 😞 
Did you manage to run this modification for a bit? If you tell me it's stable I might just go ahead and merge it. Worst that happens I can rollback the version from Steam.

**Comment by aortez** [comment] 2023-08-16 22:33
@theCrius Yup I've been playing the game the last week and with the changed code and it seems to be working correctly.

However, as it looks like a lot of people are using this mod, I think I can do a little better than just say "it works correctly now".  I'll repeat my testing and will make a quick video showing some test cases.  It's no problem.  I'll ping you once I've posted the video somewhere.

Here is what I'm thinking:
* without mod
* with mod
* with mod and changes from https://github.com/theCrius/project-zomboid-random-zombies-full/pull/10

**Comment by aortez** [comment] 2023-08-17 00:40
Ok, after testing again, things look good to me, so I think we should merge the fix. 

Here is the video link that shows my testing:
https://www.youtube.com/watch?v=wa6kpFka7v8

I tried to make it quick, in case you actually wanted to watch it, but it took me ~9 minutes to demonstrate the test cases.  Also, Youtube hasn't "verified" my channel yet, so none of the links in the video's description work, but that's fine.  My goal with creating it was to double check and document my assumptions.

One thing that I was thinking, since this mod is based on [Random Zombies](https://steamcommunity.com/sharedfiles/filedetails/?id=2818577583), it is possible that that mod also has the same bug.  I'll take a look to see later.

Hope your move is going well.

**Comment by aortez** [comment] 2023-08-17 06:35
@theCrius, so I tested another couple of mods that both have the [a very similar snippet of code](https://github.com/theCrius/project-zomboid-random-zombies-full/blob/2da53e8807c043ab1a19e8e2ad65d08786a31d0b/Contents/mods/RandomZombiesDayAndNight/media/lua/server/rzf_zombiesManager.lua#L180C24-L195) in them (Random Zombies and Definitive Zombies)... but neither of them seem to have the same issue, so now I am a little bit confused :/

Please do not take offense to this, but seeing code copy/pasted several times, with small tweaks between each version, in each different mod, this makes me wonder if we're going about adding this functionality in the right way... FWIW, Definitive Zombies seems to provide a superset of the functionality of Random Zombies - Day and Night.  However I haven't used it much so I can't really attest to how well it works.  Also I wasn't able to find the source shared in a similar way as to how you've shared it for your mod.  Sharing source on a platform designed for collaboration is a huge boon.

Anyway I still believe that my suggested changes "fix" the issue that I am experiencing with this mod (burning zeds regen health), but I wonder why I am not able to replicate it with other similar mods.  Lacking a full understanding of the issue, and no feedback from your other users that the problem is present for them, I'm not sure if merging my changes is currently warranted.  

Maybe we should just sit on my change until one of the following occurs:
* other users claim they have the same problem
* you have time to test and verify the issue/fix
* I feel like digging into the issue further and trying to figure out why I'm only seeing the problem with your mod and not the other similar ones.  If I could explain the problem better, then there may be a more direct way of solving the issue than the change that I've suggested.

**Comment by theCrius** [comment] 2023-08-17 09:00
No reason to get offended @aortez, git based development is about collaboration :)

The part about the distribution calculation was way too complex as a non-lua developer for me to dig into. I cleaned it up over time when noticing some parts that were not efficient but left most of it untouched.

I'll give a look at Definitive Zombies if I can to try and understand how they did realize the same feature. I can't recall to have ever used it, is it [this one](https://steamcommunity.com/sharedfiles/filedetails/?id=2981571303)?

**Comment by theCrius** [comment] 2023-08-17 18:01
I think that the problem is that somehow the `if` that should prevent the update is not triggering properly.

The update every _x_ amount of time is necessary otherwise you would have to rely on the in-game time like Definitive Zombies does (every 10 in game minutes) but that is a long time depending on the length of the day the player have set up and you could end up with zombies that just don't update in very long daytime settings.

What's weird is that I used the mods for a lot of time, only stopped playing zomboid for a bit (waiting for the next major update) around 6 or so months ago and that problem wasn't there. Maybe something changed in the APIs and now we have this issue.

The best option imho is to keep trying until we find what also check for the zombies taking fire damage... or if the change you implemented simply works... go with that.

**Comment by aortez** [comment] 2023-08-17 20:53
Hmm... ok well with that info then maybe my change is good enough.  I would still like to see someone else confirm the bug/fix before pushing the change to the masses... but that is just my developer instincts talking here.  The change does seem low risk, so I am not opposed to just sending it.

**Comment by theCrius** [comment] 2023-11-05 20:18
Alright, I'll consider this good to merge then

**Comment by theCrius** [comment] 2023-11-05 20:24
Closing this now, feel free to reopen if something else comes up. The update has been pushed on the steam workshop. Thanks a lot for the help!

**Closed by theCrius** 2023-11-05 20:24 UTC
